forgerock-authenticator/build.gradle
forgerock-authenticator/src/main/java/org/forgerock/android/authenticator/PushFactory.java
forgerock-authenticator/src/main/java/org/forgerock/android/authenticator/PushParser.java
forgerock-authenticator/src/main/java/org/forgerock/android/authenticator/PushResponder.java
forgerock-authenticator/src/main/java/org/forgerock/android/authenticator/util/Base32String.java
forgerock-authenticator/src/main/java/org/forgerock/android/authenticator/util/SortedList.java
forgerock-authenticator/src/main/java/org/forgerock/android/authenticator/util/TimeKeeper.java
forgerock-authenticator/src/test/java/org/forgerock/android/authenticator/AuthenticatorTestSuite.java
forgerock-authenticator/src/test/java/org/forgerock/android/authenticator/PushFactoryTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/authenticator/PushParserTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/authenticator/PushResponderTest.java

This PR includes the implementation for the following story:
SDKS-355 [Android][Authenticator SDK] Remove dependency on ForgeRock JWT library
Notes:
- The latest version of the Nimbus JWT library was used
- The change of library also required to re-write other parts of the code, once it was also using the Base64 class included in ForgeRock package.
- Some unit tests also required changes, because the "android.util.Base64" class used to replace the previous one, can't be used in a regular JUnit test, so now for those tests we are using Robolectric Runner, which is also used in "forgerock-auth" module
- Included unit tests for PushResponder class

Remove dependency on ForgeRock JWT library

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/DefaultSingleSignOnManagerTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/AccountSingleSignOnManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultSingleSignOnManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SessionManager.java

When using Android Account manager for SSO, an Account type org.forgerock and Account ForgeRock is created, since only one Account type can be created for an App, the developer may want to create Account for their own App, currently, during user logout with the SDK, the SDK removes all Account under org.forgerock, it should just remove the account created by the SDK.
Few minor enhancement for the PR:
1. Do not remove Account which is not created by SDK
2. Account Name can be provided as a parameter instead of hardcode in the file. (Internal Interface change)
3. Lazy initializing the HttpClient for OAuth2Client

SDKS-612 Should not remove Account which is not created by the SDK

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/AndroidBaseTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/FRUserTest.java

Updated the userinfo assertion in FRUserTest to check user's email, instead of username, since the "sub" attribute in most cases is a dynamic UID.

Updated the userinfo assertion in FRUserTest to check user's email

---

forgerock-auth/src/androidTest/AndroidManifest.xml

ACCESS_BACKGROUND_LOCATION permission is needed in order a couple tests to pass when running on real device (e.g: BitBar)

ACCESS_BACKGROUND_LOCATION permission added to Auth test app Manifest

---

forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
samples/auth/src/main/java/org/forgerock/auth/MainActivity.java

* Updated the public key pins for api.ipify.org - certificate has been updated, which causes test failure of the "ServerConfig" tests. 
* Added check for null for session token to avoid sample app crash upon invoking the "view tokens" option in "centralized login" scenario.

Updated the public key pins for api.ipify.org

---

CHANGELOG.md
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/FRUserTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SessionManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/TokenManager.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java
samples/auth/src/main/java/org/forgerock/auth/MainActivity.java
samples/auth/src/main/res/menu/menu.xml
samples/auth/src/main/res/values/strings.xml

Expose revoke method in FRUser
Developers will need to call Revoke and then GetAccessToken to ForceRefresh the AccessToken
Added revocation example in the Sample App

Exposing Revoke Access Token method to FRUser

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/OathTokenCode.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/OathTokenCodeTest.java

This commit exposes a new `toJson` API on the `OathTokenCode` class.
Unit test added to test this change.

SDKS-1005 Implement 'toJson' method on OathTokenCode

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/AuthenticatorManager.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/DefaultStorageClient.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/FRAClient.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/StorageClient.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/CustomStorageClient.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/FRAClientTest.java

On this change a new `getAllNotifications()` method is exposed on the FRAClient class. This will allow developers to retrieve a single list of notifications across all mechanisms.

SDKS-1006 Expose API to get all push notifications stored

---

CHANGELOG.md
forgerock-auth/build.gradle
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/AbstractValidatedCallback.java
forgerock-auth/src/test/java/org/forgerock/android/auth/AuthTestSuite.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/SerializableTest.java

JSONObject defined under AbstractValidatedCallback is not serializable, classes ValidatedUsernameCallback, ValidatePasswordCallback, StringAttributeInputCallback, NumberAttributeInputCallback, BooleanAttributeInoutCallback cannot be serialized when passing the Node object from one Activity to another.

SDKS-1486 BooleanAttributeInputCallback is not Serializable.

---

CHANGELOG.md
forgerock-auth/src/main/jni/Android.mk

SDKS-1368 Provide Build-in Binary Protection to avoid Memory Corruption Attack
Add -fstack-protector-all flag when compile native library for root detection.

SDKS-1368 Provide Build-in Binary Protection to avoid Memory Corruption Attack

---

forgerock-auth/build.gradle
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
forgerock-auth/src/test/res/values/strings.xml
forgerock-core/src/main/java/org/forgerock/android/auth/OkHttpClientProvider.java
forgerock-core/src/test/java/org/forgerock/android/auth/NetworkConfigTest.java

Align with iOS, now Android only support SHA256 SSL Pinning

SDKS-1737 Remove SHA1 Support for SSL Pinning

---

CHANGELOG.md
forgerock-authenticator/build.gradle
forgerock-authenticator/src/main/AndroidManifest.xml
forgerock-authenticator/src/main/java/org/forgerock/android/auth/DefaultStorageClient.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/NotificationFactory.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushMechanism.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushNotification.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushParser.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushResponder.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushType.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/biometric/BiometricAuth.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/biometric/BiometricAuthCompletionHandler.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/biometric/DeviceCredentialFragment.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/FRABaseTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/NotificationFactoryTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushNotificationTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushResponderTest.java
samples/authenticator/build.gradle
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/controller/AuthenticatorModel.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/controller/FcmService.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/activity/PushNotificationActivity.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/adapter/NotificationAdapter.java
samples/authenticator/src/main/res/layout/activity_push_notification.xml
samples/authenticator/src/main/res/values/styles.xml

This PR consolidates the upcoming changes on the Push Sender node ([SDKS-1472](https://bugster.forgerock.org/jira/browse/SDKS-1472)). All changes are backward compatible and Unit Tests and sample app were updated to validate the changes.
JIRA Tickets included in this PR:
[[SDKS-1666](https://bugster.forgerock.org/jira/browse/SDKS-1666)] Obtain timestamp from new Push Notification payload
[[SDKS-1776](https://bugster.forgerock.org/jira/browse/SDKS-1776)] Add new custom payload in the Push Notification
[[SDKS-1454](https://bugster.forgerock.org/jira/browse/SDKS-1454)] Sample app crash after scan push mechanism

SDKS-1666, SDKS-1776 - Push Notification enhancements

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/MechanismParser.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/OathParserTest.java

[SDKS-1408](https://bugster.forgerock.org/jira/browse/SDKS-1408) Discrepancies between Android and iOS behavior upon registering OATH account (Issuer param)
While registering a new mechanism, if "issuer" is empty on the query parameter of the URI, but available in the path, the SDK should not throw exception. Instead, it should use the issue in the path.

SDKS-1408 Discrepancies between Android and iOS behavior upon registering OATH account (Issuer param)

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultTokenManager.java
forgerock-auth/src/test/java/org/forgerock/android/auth/DefaultTokenManagerTest.java

[SDKS-2066](https://bugster.forgerock.org/jira/browse/SDKS-2066)
Cache the access token after retrieval from local storage, to enable the cache forgerock_oauth_cache needs to set to a value > 0.

SDKS-2066 DefaultTokenManager does not cache the access token upon retrieval from local storage.

---

.github/workflows/run-live-tests.yaml

[SDKS-1789](https://bugster.forgerock.org/jira/browse/SDKS-1789) "Automate Cloud Upgrade Testing"
This PR adds workflow for triggering the e2e test cases against live IDCloud environment. The workflow is called "Run Live Tests".
The e2e tests now can be triggered either manually from the "Actions" menu in the repo, or via an HTTP request. 
Triggering the workflow via HTTP request requires a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) (PAT) passed as a Bearer token in the Authorization header. For more details read the [workflow-dispatch-event](https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event) docs.

Automate Cloud Upgrade Testing [SDKS-1789]

---

CHANGELOG.md
gradle.properties

[SDKS-2103](https://bugster.forgerock.org/jira/browse/SDKS-2103) "ForgeRock Android SDK 3.4.0 Release"
Fix release version to **3.4.0**

ForgeRock Android SDK 3.4.0 release preparation (fix release version)

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/CustomDeviceSigningVerifierCallback.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt

[SDKS-2025](https://bugster.forgerock.org/jira/browse/SDKS-2025) "JWS Verifier QA"
- Added e2e tests for the Device Signing Verifier node
- Updated temporarily the `DeviceSigningVerifierCallback` class, so that I don't break the build. A proper fix for these will be done with [SDKS-2132](https://bugster.forgerock.org/jira/browse/SDKS-2132).
- The e2e test cases require a specific `device-verifier` authentication tree, which is currently present in the https://openam-dbind.forgeblocks.com/am instance. To better understand the test cases please take a look at the tree first. The following is a screenshot of it: 
- testDeviceSigningVerifierCallbackDefaults
- testDeviceSigningVerifierCallbackCustom
- testDeviceVerificationSuccess
- testDeviceVerificationSuccessCustomExp
- …

SDKS-2025 JWS Verifier QA

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/Binding.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticator.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindingStatus.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/SharedPreferencesDeviceRepository.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticatorTest.kt
forgerock-core/src/main/java/org/forgerock/android/auth/AppPinAuthenticator.kt
forgerock-core/src/main/java/org/forgerock/android/auth/CryptoKey.kt

SDKS-2091
SDKS-2091 Remove Keys after the binding process is failed
When the binding process is triggered, it generates new keys and replaces existing keys, after authentication failed, the newly generated keys are left behind in the device. During the process of Device Signing Verification, since there is a generated keys, it triggered the authentication process, but the keys do not match with the server, and make the signing process failed. To resolve this, when authentication failed, it removes the keys, and the user is required to perform rebinding again.

SDKS-2091 Remove Keys after the binding process is failed

---

CHANGELOG.md
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/WebAuthnRegistrationCallbackFragment.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/WebAuthnCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/WebAuthnRegistrationCallback.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/WebAuthnRegistrationCallbackTest.kt

https://bugster.forgerock.org/jira/browse/SDKS-2296
SDKS-2296 Interface to set device name during WebAuthn Registration

SDKS-2296 Interface to set device name during WebAuthn Registration

---

README.md
build.gradle
config/kdoc.gradle
dokka/fr-backstage-styles.css
dokka/logo-icon.svg
dokka/templates/base.ftl
dokka/templates/page_metadata.ftl

[SDKS-2334](https://bugster.forgerock.org/jira/browse/SDKS-2334)
[SDKS-2123](https://bugster.forgerock.org/jira/browse/SDKS-2123) provided the foundation of the kdoc kotlin docs generation (gradle tasks etc...). 
The generated docs however needs to be customized - i.e. use ForgeRock logo/favicon, footer, etc... 
Acceptance criteria: 
The generated kdocs uses ForgeRock branding (Logo, footer, navigation area)
Notes:
See https://kotlinlang.org/docs/dokka-html.html#configuration

SDKS-2334 - Add BackStage Docs theme to HTML and JavaDoc outputs.

---

README.md
build.gradle
config/kdoc.gradle
dokka/fr-backstage-styles.css
dokka/logo-icon.svg
dokka/templates/base.ftl
dokka/templates/page_metadata.ftl

[SDKS-2334](https://bugster.forgerock.org/jira/browse/SDKS-2334)
**Problem description:** 
[SDKS-2123](https://bugster.forgerock.org/jira/browse/SDKS-2123) provided the foundation of the kdoc kotlin docs generation (gradle tasks etc...). 
The generated docs however needs to be customized - i.e. use ForgeRock logo/favicon, footer, etc... 
**Acceptance criteria:** 
The generated kdocs uses ForgeRock branding (Logo, footer, navigation area)
**Notes:**
See https://kotlinlang.org/docs/dokka-html.html#configuration

[improve][doc] Add BackStage Docs theme to HTML and JavaDoc outputs. (SDKS-2334)

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/AuthenticatorManager.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/FRAClient.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/MechanismParser.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/AuthenticatorManagerTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/FRAClientTest.java

[SDKS-2407](https://bugster.forgerock.org/jira/browse/SDKS-2407) Attempt to update locked account should throw an exception
When invoking FRClient.updateAccount(), it should throw the AccountLockException if the account is locked.

SDKS-2407 Attempt to update locked account should throw an exception

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticator.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticatorTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticationTests.kt

[SDKS-2450](https://bugster.forgerock.org/jira/browse/SDKS-2450)
Instead of fixing this issue, we decided to not support Key Attestation for API Level 23.
When using API Level 23, will route to unsupported outcome.

SDKS-2450 Key Attestation will not support API Level 23

---

CHANGELOG.md
gradle.properties

[SDKS-2547](https://bugster.forgerock.org/jira/browse/SDKS-2547) ForgeRock Android SDK 4.1.0-beta1 Release
Release preparation for the ForgeRock Android SDK 4.1.0-beta1. 
This release include only one bug-fix in the Authenticator module - [SDKS-2542](https://bugster.forgerock.org/jira/browse/SDKS-2542) [FRA] Combined MFA Registration not working properly

ForgeRock Android SDK 4.1.0-beta1 Release

---

CHANGELOG.md
gradle.properties

[SDKS-2572](https://bugster.forgerock.org/jira/browse/SDKS-2572) ForgeRock Android SDK 4.1.0-beta2 Release

ForgeRock Android SDK 4.1.0-beta2 release preparation

---

CHANGELOG.md
forgerock-authenticator/src/main/java/org/forgerock/android/auth/AuthenticatorManager.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/AuthenticatorManagerTest.java

[SDKS-2627](https://bugster.forgerock.org/jira/browse/SDKS-2627) Combined MFA should throw DuplicatedMechanismException for existing accounts
While registering a Combined MFA account, the SDK should throw a Duplicated mechanism error if any of the included mechanisms is already registered on the app.

Combined MFA should throw DuplicatedMechanismException

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/FRUserTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultTokenManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SessionManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/TokenManager.java
forgerock-auth/src/test/java/org/forgerock/android/auth/DefaultTokenManagerTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java
samples/app/src/main/java/com/example/app/token/Token.kt
samples/app/src/main/java/com/example/app/token/TokenState.kt
samples/app/src/main/java/com/example/app/token/TokenViewModel.kt

https://bugster.forgerock.org/jira/browse/SDKS-2617
Revoke old access token upon force refresh

SDKS-2617 Revoke old access token upon force refresh

---

.github/workflows/ci.yaml

Fixed permissions in ci.yaml for dependabot.

Fix CI permissions for GITHUB_TOKEN

---

forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-auth/src/main/java/org/forgerock/android/auth/idp/FacebookSignInHandler.java
forgerock-authenticator/build.gradle
forgerock-core/build.gradle
samples/app/build.gradle
samples/app/src/main/AndroidManifest.xml
samples/app/src/main/res/values/strings.xml
samples/auth/build.gradle
samples/authenticator/build.gradle
samples/kotlin/build.gradle
samples/quickstart/build.gradle

[SDKS-2636](https://bugster.forgerock.org/jira/browse/SDKS-2636)
Android 14 Support, update compileSdk to 34 for all projects:
The following Sanity test has been performed on Android 14 Device:
1. Centralize Login
2. Facebook Login
3. Google Login
4. WebAuthn Registration and Authentication
5. Device Binding and Verification
6. Simple Username and Password Authentication

SDKS-2636 Android 14 Support

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/exception/WebAuthnResponseException.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/WebAuthnFragment.kt

https://bugster.forgerock.org/jira/browse/SDKS-2819
Handle WebAuthn Cancellation inconsistency, Google FIDO library may return Activity.RESULT_CANCELED instead of AuthenticatorErrorResponse with NOT_ALLOW_ERROR when cancelling the FIDO authentication process, the SDK handles both scenario, and translate Activity.RESULT_CANCELED to WebAuthn NOT_ALLOW_ERROR

SDKS-2891 Handle WebAuthn Cancellation inconsistency

---

forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/CallbackFragmentFactory.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/AppIntegrityCallbackFragment.java
forgerock-auth-ui/src/main/res/layout/fragment_app_integrity_callback.xml
forgerock-auth/build.gradle
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/AppIntegrityCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/AppIntegrityNodeListener.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/BaseDeviceBindingTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingListAndUnbind.java
samples/auth/build.gradle

[SDKS-2784](https://bugster.forgerock.org/jira/browse/SDKS-2784) [Android] App Integrity QA
- Added e2e test cases for the App Integrity feature. These test cases work with "live" AM server and require the following authentication tree:
At this moment the test cases will run against the https://localam.petrov.ca/openam instance (which contains this tree and additional configurations)...
- Updated the `auth` sample app - added support for `AppIntegrityCallback`
- Switched the device binding test cases to run against https://openam-sdks.forgeblocks.com/am

SDKS-2784 Test coverage for the App Integrity feature

---

.github/workflows/bitbar-prepare-artifacts.yaml
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/BaseDeviceBindingTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/CustomDeviceSigningVerifierCallback.kt
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java

[SDKS-2935](https://bugster.forgerock.org/jira/browse/SDKS-2935): If a user is set to `inactive` the `DeviceSigningVerifier` node throws an exception
- Added test coverage for the `Capture Failure` option in the Device Signing Verifier node
- Added test coverage for the `DeviceSigningVerifierNode.FAILURE` shared state variable

SDKS-2935 Added test coverage the failure outcome in the DeviceSigningVerifier node

---

CHANGELOG.md
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/AppIntegrityCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/BaseDeviceBindingTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
gradle.properties

[SDKS-2963](https://bugster.forgerock.org/jira/browse/SDKS-2963) ForgeRock Android SDK 4.3.1 Release
- Updated `CHANGELOG.md`
- Update the version number in `gradle.properties` file
- Fixed `device bind` and `device singing` test cases (the IDCloud instance)
- Fixed SSL pinning test cases (the certificate of `api.ipify.org` has been recently updated)

ForgeRock Android SDK 4.3.1 Release Preparation

---

forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/CallbackFragmentFactory.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/TextInputCallbackFragment.java
forgerock-auth-ui/src/main/res/layout/fragment_text_input_callback.xml
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/TextInputCallbackTest.java
forgerock-auth/src/androidTest/res/values/strings.xml
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/CallbackFactory.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/TextInputCallback.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/TextInputCallbackTest.kt
samples/app/src/main/java/com/example/app/callback/TextInputCallback.kt
samples/app/src/main/java/com/example/app/journey/Journey.kt

[SDKS-545](https://bugster.forgerock.org/jira/browse/SDKS-545) TextInputCallback Support
Adding support in the SDK to handle the TextInputCallback and provide a corresponding samples.

SDKS 545 - TextInputCallback Support

---

forgerock-auth/src/main/java/org/forgerock/android/auth/AppAuthFragment.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/test/java/org/forgerock/android/auth/BrowserLoginTest.kt

N/A
Hello Forgerock team!
On our project, we've encountered an issue when android app is crashing with the following stack trace:
```
android.content.ActivityNotFoundException
at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:555)
at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:390)
at org.forgerock.android.auth.AppAuthFragment.onCreate(AppAuthFragment.java:90)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:19 …
```

Make ActivityNotFoundException to be intercepted by FRListener

---

forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/AndroidBaseTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/FRDeviceProfileTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/RetryTestRule.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/SkipTestOnPermissionFailureRule.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/BaseDeviceBindingTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingNodeListener.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/DeviceProfileCollectorCallbackAndroidTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/KeyAttestationTest.java

[SDKS-3015](https://bugster.forgerock.org/jira/browse/SDKS-3015) SDK 4.4.0 Release Testing
Some of the device binding/signing e2e test cases were failing when running in parallel on multiple devices, because they were using the same user and some assumptions were not met - for example, some a test may make the user inactive, and at the same time, other tests assume/require that the same user is active...
For that reason, I introduced the following improvements: 
- All device binding/signing related test cases now create a brand new random user...
- Introduced a `RetryTestRule` annotation and added it to the device binding tests. This way a test would be repeated 3 times if it fails... This is useful for flaky tests...
- "Suppressed" the `KeyAttestation` e2e test cases on Android 6, since …

SDKS-3015 SDK 4.4.0 Release Testing

---

.github/workflows/build-and-test.yaml
.github/workflows/ci.yaml
README.md
build.gradle.kts
config/jacoco.gradle
forgerock-auth/build.gradle.kts
forgerock-authenticator/build.gradle.kts
forgerock-core/build.gradle.kts
ping-protect/build.gradle.kts

[SDKS-3180](https://bugster.forgerock.org/jira/browse/SDKS-3180) Add test coverage report to Android SDK pipeline
- Added test coverage report to the `forgerock-core`, `forgerock-auth`, `forgerock-authenticator`, and `ping-protect` modules

SDKS-3180 Add Jacoco test coverage report

---

CHANGELOG.md
build.gradle.kts
forgerock-auth/src/test/java/org/forgerock/android/auth/AuthServiceMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/BaseTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/BrowserLoginTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/DefaultTokenManagerTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/DeviceBindingRepositoryTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRAuthMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRAuthRegistrationMockTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRLifeCycleListenerTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRSessionMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/OAuth2MockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/PersistentCookieTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/PolicyAdviceTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverIntegrationTests.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/SocialLoginTest.java
forgerock-authenticator/build.gradle.kts
forgerock-core/build.gradle.kts
forgerock-core/src/test/java/org/forgerock/android/auth/NetworkConfigTest.java
forgerock-core/src/test/java/org/forgerock/android/auth/RequestInterceptorTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/MockServer.java
gradle/libs.versions.toml

[SDKS-3073](https://bugster.forgerock.org/jira/browse/SDKS-3073)
[SDKS-3072](https://bugster.forgerock.org/jira/browse/SDKS-3072)
[SDKS-3215](https://bugster.forgerock.org/jira/browse/SDKS-3215)
SDKS-3073 Resolve commons-io-2.6.jar and bcprov-jdk15on-1.68.jar vulnerability warning
Upgraded to commons-io = "2.16.1"
The commons-io is only used for testing, no production code is changed.
Remove force("org.bouncycastle:bcprov-jdk15on:1.68") version and upgrade to use okhttp3.mockserver 4.12.0
The org.bouncycastle library is used by mockserver, upgrade the mockserver will also upgrade the bouncycastle

SDKS-3073 Resolve commons-io-2.6.jar and bcprov-jdk15on-1.68.jar vulnerability warning

---

CHANGELOG.md
forgerock-core/src/main/java/org/forgerock/android/auth/AppPinAuthenticator.kt

…
[SDKS-3221](https://bugster.forgerock.org/jira/browse/SDKS-3221)
SDKS-3221 uses English locale when generating certificate for Application Pin

SDKS-3221 uses English locale when generating certificate for Application Pin

---

forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/FRWebAuthn.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/WebAuthnRegistration.kt

[SDKS-3244](https://bugster.forgerock.org/jira/browse/SDKS-3244) Fix "usernameless" WebAuthn Tests
This reverts a previous change where the PublicKeyCredentialSource where stored for all WebAuthn use cases.

SDKS-3244 Only store PublicKeyCredentialSource when requireResidentKey is true

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SessionManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/AppAuthFragment2.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/AuthorizeContract.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/BrowserLauncher.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/EndSessionContract.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/Launcher.kt
samples/app/src/main/java/com/example/app/LogoutViewModel.kt
samples/app/src/main/java/com/example/app/centralize/CentralizeLoginViewModel.kt
samples/app/src/main/java/com/example/app/env/EnvViewModel.kt

SDKS-3276 - Unable to signout user with browser when using different browser to signout. 
SDKS-3277 - The AppAuthConfiguration settings are being ignored during centralized login, causing unexpected behavior in the authentication flow.
[SDKS-3276](https://bugster.forgerock.org/jira/browse/SDKS-3276)
[SDKS-3277](https://bugster.forgerock.org/jira/browse/SDKS-3277)
Custom browser sample to SignIn with browser and Signout with browser
SignIn
```kotlin
FRUser.browser().appAuthConfigurer().customTabsIntent {
it.setColorScheme(CustomTabsIntent.COLOR_SCHEME_DARK)
}.appAuthConfiguration { appAuthConfiguration ->
appAuthConfiguration.setBrowserMatcher(
BrowserDenyList(
VersionedBrowserMatcher.CHROME_CUSTOM_TAB,
VersionedBrowserMatcher.CHROME_BROWSER
)
)
}
.done()
.login(fragmentActivity,
object : …
```

SDKS-3276 & SDKS-3277

---

forgerock-auth/src/main/java/org/forgerock/android/auth/ConfigHelper.kt
forgerock-auth/src/main/res/values/strings.xml
forgerock-auth/src/test/java/org/forgerock/android/auth/ConfigHelperTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java
forgerock-auth/src/test/res/values/strings.xml

[SDKS-3279](https://bugster.forgerock.org/jira/browse/SDKS-3279)
SDKS-3279 Support file base configuration for forgerock_oauth_sign_out_redirect_uri
Centralize logout for PingOne, make sure to override the oauth path
```
<string name="forgerock_authorize_endpoint" translatable="false">https://auth.pingone.ca/$EnvId/as/authorize</string>
<string name="forgerock_token_endpoint" translatable="false">https://auth.pingone.ca/$EnvId/as/token</string>
<string name="forgerock_revoke_endpoint" translatable="false">https://auth.pingone.ca/$EnvId/as/revoke</string>
<string name="forgerock_userinfo_endpoint" translatable="false">https://auth.pingone.ca/$EnvId/as/userinfo</string>
<string name="forgerock_endsession_endpoint" translatable="false" >https://auth.pingone.ca/$EnvId/as/signoff</string>
```

SDKS-3279 Support file base configuration for forgerock_oauth_sign_out_redirect_uri

---

forgerock-auth/src/main/java/org/forgerock/android/auth/FRAuth.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
forgerock-auth/src/main/res/values/strings.xml

[SDKS-3284](https://bugster.forgerock.org/jira/browse/SDKS-3284)
- Validate the server url before persist, for now, it does not validate the format, just make sure it is not empty.
- Ignore exception when failed to load the stored configuration.

SDKS-3284 Inconsistent behavior when forgerock_url is not provided.

---

forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
forgerock-auth/src/main/java/org/forgerock/android/auth/ConfigHelper.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ConfigHelperTest.kt

[SDKS-3283](https://bugster.forgerock.org/jira/browse/SDKS-3283) Starting the SDK with different configuration does NOT end user's session 
- Updated the `ConfigHelper` class to store the `signOutRedirectUri` into the share preferences
- Added back the getters to the path config variables (`authenticateEndpoint`, `authorizeEndpoint`, `tokenEndpoint`, `revokeEndpoint`, `userinfoEndpoint`, `sessionEndpoint`, `endSessionEndpoint`) to align the behavior with iOS

SDKS-3283 Persisting the signOutRedirectUri into the shared preferences.

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/Node.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/TextOutputCallback.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/TextOutputCallbackTest.kt
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/TextOutputCallbackTest.java
samples/app/src/main/java/com/example/app/callback/TextOutputCallback.kt
samples/app/src/main/java/com/example/app/journey/Journey.kt

Added conditional sbmittion of TextOutput Callbacks based on the type skipping 4
Updated the sample apps to handle the ScriptedTextOutputCallbacks and long content better
[Please link jira ticket here](https://bugster.forgerock.org/jira/browse/SDKS-3227)
Added conditional sbmittion of TextOutput Callbacks based on the type skipping 4
Updated the sample apps to handle the ScriptedTextOutputCallbacks and long content better

SDKS-3227_Skipping type 4 TextOutputCallbacks

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/AbstractProtectCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/MetadataCallback.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/MetadataCallbackTest.kt
forgerock-auth/src/test/resources/protect_initialize.json
forgerock-auth/src/test/resources/protect_risk_evaluation.json
ping-protect/src/main/java/org/forgerock/android/auth/PingOneProtectEvaluationCallback.kt
ping-protect/src/main/java/org/forgerock/android/auth/PingOneProtectInitializeCallback.kt
ping-protect/src/test/java/org/forgerock/android/auth/PingOneProtectEvaluationCallbackTest.kt
ping-protect/src/test/java/org/forgerock/android/auth/PingOneProtectInitializeCallbackTest.kt

[SDKS-3297](https://bugster.forgerock.org/jira/browse/SDKS-3297) [Android] Support Marketplace PingOne Protect nodes
Make sure that the Android SDK supports the PingOne Protect nodes offered in the Marketplace, which utilized the MetadataCallback.

SDKS-3297 Support MetadataCallback used by Marketplace PingOne Protect

---

forgerock-auth/src/main/java/org/forgerock/android/auth/RetrieveAccessTokenInterceptor.java

[SDKS-3426](https://bugster.forgerock.org/jira/browse/SDKS-3426)
SDKS-3426 When compare the SessionToken associated with the AccessToken, it should just compare the value but not the SSOToken Object.

SDKS-3426 When compare the SessionToken associated with the AccessToken, it should just compare the value but not the SSOToken Object.

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
samples/app/src/main/AndroidManifest.xml

[SDKS-3433](https://bugster.forgerock.org/jira/browse/SDKS-3433)
Allow http/https as redirect scheme
assetLinks.json for the sample App has been setup for idc.petrov.ca
https://idc.petrov.ca/.well-known/assetlinks.json
Update AndroidManifest.xml to use http/https scheme
Make sure it has autoVerify=true
```xml
<activity
android:name="net.openid.appauth.RedirectUriReceiverActivity"
android:exported="true"
tools:node="replace">
<intent-filter android:autoVerify="true">
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
<data android:scheme="https" />
<data android:host="idc.petrov.ca" />
<data android:path="/oauth2redirect" />
</intent-filter>
</activity>
``` 
More …

SDKS-3433 Allow http/https as redirect scheme

---

forgerock-auth/src/main/java/org/forgerock/android/auth/selfservice/Device.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/selfservice/DeviceClient.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/selfservice/DeviceClientMockTest.kt
samples/app/src/main/java/com/example/app/selfservice/SelfServiceRoute.kt
samples/app/src/main/java/com/example/app/selfservice/SelfServiceViewModel.kt

[SDKS-3571](https://pingidentity.atlassian.net/browse/SDKS-3571)
Align Device Management interface.
```kotlin
//To Retrieve the devices
deviceClient.oath.get()
deviceClient.push.get()
deviceClient.webAuthn.get()
deviceClient.bound.get()
deviceClient.profile.get()
//To Update the devices
deviceClient.webAuthn.update(WebAuthnDevice)
deviceClient.bound.update(BoundDevice)
deviceClient.profile.update(ProfileDevice)
//To Delete the device
deviceClient.oath.delete(OathDevice)
deviceClient.push.delete(PushDevice)
deviceClient.webAuthn.delete(WebAuthnDevice)
deviceClient.bound.delete(BoundDevice)
deviceClient.profile.delete(ProfileDevice)
```

SDKS-3571 Align Device Management interface with other platforms

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/AuthenticatorManager.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/DefaultStorageClient.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/FRAClient.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/NotificationFactory.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/StorageClient.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/AuthenticatorManagerTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/CustomStorageClient.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/DefaultStorageClientTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/FRAClientTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/NotificationFactoryTest.java

[SDKS-3697](https://pingidentity.atlassian.net/browse/SDKS-3697) Prevent duplicated notification on the SDK
The Android SDK does not verify whether a push notification with an identical message identifier has already been stored, delegating this responsibility to the application developer. This PR include the following changes:
- Added a new `getNotificationByMessageId` method to the StorageClient and FRAClient
- Updated the logic to check whether a payload was already persisted
- Update unit tests

SDKS-3697 Prevent duplicated notification on the SDK

---

CHANGELOG.md
README.md

[SDKS-3707](https://pingidentity.atlassian.net/browse/SDKS-3707)
Updating links that went to BackStage.

SDKS-3707 Update documentation links in README files.

---

build.gradle.kts

[SDKS-3750](https://pingidentity.atlassian.net/browse/SDKS-3750)
Resolve High Severity Vulnerability WS-2022-0468 in jackson-core-2.13.5.jar by upgrading the dokka plugin

SDKS-3750 Resolve High Severity Vulnerability WS-2022-0468 in jackson-core-2.13.5.jar

---

forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultTokenManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SingleSignOnInterceptor.java
forgerock-auth/src/main/java/org/forgerock/android/auth/TokenManager.java
forgerock-core/src/main/java/org/forgerock/android/auth/BiConsumer.java

[SDKS-3772](https://pingidentity.atlassian.net/browse/SDKS-3772)
SDKS-3772 Revoke and terminate the session when it does not match the existing session.

SDKS-3772 Revoke and terminate the session when it does not match the existing session.

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushNotification.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushNotificationTest.java

[SDKS-4286](https://pingidentity.atlassian.net/browse/SDKS-4286) [RFE] [FRA] - SDK sets isExpired flag out of sync with the server's attitude
Previously, the `isExpired` method in `PushNotication` was comparing the `timeExpired` value against the device's current time via `Calendar.getInstance(TimeZone.getTimeZone("UTC"))`. This makes the expiration check vulnerable to device clock manipulation. The logic was updated to make it more resilient by calculating the TTL based on the elapsed time since the notification was received, rather than directly comparing to the system time. This change also makes things consistent with how it already works on iOS.

SDKS-4286 Update isExpired method in the PushNotification class to address out-of-sync scenarios

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushNotification.java

[SDKS-4286](https://pingidentity.atlassian.net/browse/SDKS-4286) SDK sets `isExpired` flag out of sync with the server's attitude
- Updated the "isExpired" logic the same as on iOS implementation

SDKS-4286 Update the "isExpired" logic the same as on iOS implementation

---

README.md
buildSrc/src/main/kotlin/AndroidBuildGradlePlugin.kt
e2e/app/build.gradle.kts
forgerock-auth-ui/build.gradle

[SDKS-4409](https://pingidentity.atlassian.net/browse/SDKS-4409?actionerId=712020%3A63898f22-4b5d-4737-b2d3-acf2ca9b9133&sourceType=assign)
Set minimum SDK version to 23 in build configuration files
Revert change from SDK version change from 28 back to 23.

SDKS-4409: Revert change from SDK version change from 28 back to 23
