ForgeRock/forgerock-android-sdk

app/src/main/res/values/strings.xml
build.gradle
forgerock-auth/src/main/java/org/forgerock/android/auth/AccountSingleSignOnManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/AuthServiceClient.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultSingleSignOnManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultTokenManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SharedPreferencesSignOnManager.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRAuthMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java

Rollback version changes and Store SSO Token even when SSO is not configured

Sdks 127 - Rollback version changes and Store SSO Token even when SSO is not configured

---

forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/test/java/org/forgerock/android/auth/AuthServiceMockTest.java

SDKS-125 Change /authorize endpoint from POST to GET.

SDKS-125 Change /authorize endpoint from POST to GET.

---

CHANGELOG.md
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/CallbackFragmentFactory.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/LoginFragment.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/AdaptiveCallbackFragment.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/CallbackController.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/CallbackFragment.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/ConfirmationCallbackFragment.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/DeviceProfileCallbackFragment.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/NameCallbackFragment.java
forgerock-auth-ui/src/main/res/values/colors.xml
forgerock-auth-ui/src/main/res/values/strings.xml
forgerock-auth-ui/src/main/res/values/styles.xml
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/AuthInstrumentTestSuite.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceProfileCollectorCallbackAndroidTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/InterceptorHandler.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/Callback.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/CallbackFactory.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/ConfirmationCallback.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceProfileCallback.java
forgerock-auth/src/main/java/org/forgerock/android/auth/collector/DeviceCollector.java
forgerock-auth/src/main/java/org/forgerock/android/auth/collector/FRDeviceCollector.java
forgerock-auth/src/main/java/org/forgerock/android/auth/collector/MetadataCollector.java
forgerock-auth/src/test/java/org/forgerock/android/auth/AuthTestSuite.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceProfileCollectorCallbackTest.java

Support Device Profile Collector Node

SDKS-293 Support Device Profile Collector Node

---

README.md

Signed-off-by: Chris Lee (ForgeRock) <chris.lee@forgerock.com>

SDK-263 Unify README files in ForgeRock SDK projects.

---

forgerock-authenticator/build.gradle
forgerock-authenticator/src/test/java/org/forgerock/android/auth/AuthenticatorTestSuite.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/OathCodeGeneratorTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/OathFactoryTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushFactoryTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushParserTest.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/controller/AuthenticatorModel.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/activity/AccountsActivity.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/activity/AddMechanismActivity.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/adapter/AccountAdapter.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/layout/AccountLayout.java
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/layout/MechanismIconLayout.java

This pull request also includes the PR #45 to avoid merge conflicts.

Sdks 469 command line test run

---

forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-authenticator/build.gradle
forgerock-core/build.gradle

Update SDK Version Code and Version Name for 2.1.0 release

SDKS-584 Update SDK version code and version name.

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/AndroidBaseTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/BooleanAttributeInputCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/ChoiceCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/ConsentMappingCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceProfileCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/KbaCreateCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/NameCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/NumberAttributeInputCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/PageCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/PasswordCallbackTest.java
forgerock-auth/src/androidTest/res/values/strings.xml

Updated FRAuth e2e test cases to run against live environment. (SDKS-516)

Live e2e test cases

---

README.md
forgerock-auth/build.gradle
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushResponderTest.java

- Fixed build.gradle so that we can build the project from the command line
- Added build status badge in README.md
- Fixed the testShouldSignJWTCorrectly test (it was failing randomly)

CI/CI Fixes

---

samples/auth/build.gradle
samples/auth/src/main/AndroidManifest.xml

Keep MANAGE_ACCOUNTS permission for sample App to run on Android 5.1

SDKS-1050 Keep MANAGE_ACCOUNTS permission for sample App

---

samples/auth/src/main/AndroidManifest.xml

Add "exported" attribute for Activity with intent-filter

SDKS-1148 Android 12 Support - Add "exported" attribute for Activity

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/WebAuthnHeadlessAuthenticateFragment.java
forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/WebAuthnHeadlessRegistrationFragment.java

SDKS-1297 Remove existing fragment and re-initiate the WebAuthn Fragment when receive WebAuthn Callbacks.

---

forgerock-auth/src/main/java/org/forgerock/android/auth/FRSession.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/Node.java

Add Exception description to javadoc.

SDKS-1465 Exception documentation

---

forgerock-auth/build.gradle
samples/auth/build.gradle

SDKS-1510 Upgrade facebook sdk to support Android 12

SDKS-1510 Upgrade facebook sdk to support Android 12

---

.gitignore
forgerock-auth/src/main/java/org/forgerock/android/auth/SSOBroadcastModel.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/SSOBroadcastReceiver.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastModelTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverIntegrationTests.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverTest.kt
forgerock-authenticator/build.gradle
forgerock-authenticator/src/test/java/org/forgerock/android/auth/FRABaseTest.java
forgerock-core/src/test/java/org/forgerock/android/auth/RequestInterceptorTest.java
samples/authenticator/.gitignore
samples/authenticator/google-services.json

This Story fixes the delay broadcast issue  for few devices
And we stop making logout calls when the broadcast happen from another app 
Also added new integration test

SDKS-1676 & SDKS 1717

---

forgerock-auth/src/main/java/org/forgerock/android/auth/AuthService.java
forgerock-auth/src/main/java/org/forgerock/android/auth/AuthServiceResponseHandler.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultSingleSignOnManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultTokenManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2ResponseHandler.java
forgerock-auth/src/main/java/org/forgerock/android/auth/UserService.java

Provide more debug log for developer to debug the SDK State.

SDKS-1925 Extra debug log

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/bitbar-results.yaml
.github/workflows/bitbar-run.yaml
.github/workflows/build-and-test.yaml
.github/workflows/ci.yaml
forgerock-auth/src/androidTest/res/values/strings.xml

[SDKS-1769](https://bugster.forgerock.org/jira/browse/SDKS-1769): Execute e2e tests on BitBar via Github actions
- Split all workflows into smaller chunks
- Added workflows for preparing and running e2e test on BitBar
- Test summary of the results is published to slack

Execute e2e tests on BitBar via Github actions

---

forgerock-core/src/main/java/org/forgerock/android/auth/DefaultLogger.kt
forgerock-core/src/main/java/org/forgerock/android/auth/Logger.kt
forgerock-core/src/test/java/org/forgerock/android/auth/InterceptorProviderTest.kt
forgerock-core/src/test/java/org/forgerock/android/auth/LoggerUnitTest.kt

SDKS-1864 custom logger Part-2

---

CHANGELOG.md
README.md
gradle.properties
samples/auth/build.gradle

[SDKS-1943](https://bugster.forgerock.org/jira/browse/SDKS-1943) ForgeRock Android SDK 3.3.2 Release
ForgeRock Android SDK 3.3.2 Release Preparation

ForgeRock Android SDK 3.3.2 release preparation

---

forgerock-auth/build.gradle
forgerock-authenticator/build.gradle
forgerock-core/build.gradle
samples/auth/build.gradle

https://bugster.forgerock.org/jira/browse/SDKS-1957
[Briefly describe the change and any information that would help speedup the review and testing.](https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-4ffcc7ad816065-1655767665-10650cb5c7764e0fbcf4860abfa8d8b3)

SDKS-1957 - bumped the okhttp version for security vulneriability

---

CHANGELOG.md

[SDKS-1959](https://bugster.forgerock.org/jira/browse/SDKS-1959) ForgeRock Android SDK 3.3.3 release preparation
Fix ticket number in the changelog.

ForgeRock Android SDK 3.3.3 release preparation

---

CHANGELOG.md
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushNotification.java

SDKS-1968 Wrong type of Activity in accept method of PushNotification

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/CookieMarshaller.java

deserializing an object with whitelist.
https://bugster.forgerock.org/jira/browse/SDKS-1818
When deserializing an object, make sure the object class is expected.

SDKS-118 Deserializing an object with whitelist.

---

.lift.toml
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/FRSessionViewModel.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceProfileCallbackTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
forgerock-auth/src/main/java/org/forgerock/android/auth/ConfigHelper.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/FRAuth.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/SSOBroadcastModel.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/SSOBroadcastReceiver.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/BaseTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/ConfigHelperTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRAuthMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRDeviceTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FROptionTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastModelTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceProfileCollectorCallbackTest.java
samples/kotlin/src/main/AndroidManifest.xml
samples/kotlin/src/main/java/com/forgerock/kotlinapp/FRSessionActivity.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/NodeDialogFragment.kt

SDKS-1759 Dynamic config

---

forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
forgerock-auth/src/main/java/org/forgerock/android/auth/ConfigHelper.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/FRAuth.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FROptions.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SSOBroadcastReceiver.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ConfigHelperTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/FRAuthMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverIntegrationTests.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverTest.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/FRSessionActivity.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/MainActivity.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/NodeDialogFragment.kt

SDKS - 2031 Bugs fixed when change on client_id to load from persisted options

---

forgerock-auth/src/main/res/values/strings.xml
forgerock-auth/src/test/res/values/strings.xml

[SDKS-2609](https://bugster.forgerock.org/jira/browse/SDKS-2069)
Remove all occurrences of forgerock_enable_cookie

SDKS-2069  forgerock_enable_cookie configuration not being used

---

CHANGELOG.md
forgerock-authenticator/build.gradle
samples/authenticator/build.gradle
samples/authenticator/src/main/AndroidManifest.xml
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/view/activity/AccountsActivity.java

[SDKS-2033](https://bugster.forgerock.org/jira/browse/SDKS-2033) Authenticator- Android 13 Push notification changes
Updated the `forgerock-authenticator` module and `authenticator` sample app to handle the new `POST_NOTIFICATIONS` permission introduced on Android 13 (API 33).

SDKS-2033 Authenticator- Android 13 Push notification changes

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/ServerConfig.java
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java

[Please link jira ticket here](https://bugster.forgerock.org/jira/browse/SDKS-2074)
Allow leading slash on custom endpoint path

SDKS-2074 Path related configurations causing request failures when the values contain forward slash

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2ResponseHandler.java
forgerock-auth/src/test/java/org/forgerock/android/auth/AuthServiceMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRAuthRegistrationMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRLifeCycleListenerTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/FRUserMockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/OAuth2MockTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/SSOBroadcastReceiverIntegrationTests.kt

https://bugster.forgerock.org/jira/browse/SDKS-2078
Generate and verify state value for /authorize endpoint

SDKS-207 State value is not verified

---

forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultSingleSignOnManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/RetrieveAccessTokenInterceptor.java
forgerock-auth/src/main/java/org/forgerock/android/auth/SSOBroadcastModel.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/SingleSignOnManager.java
samples/auth/build.gradle
samples/auth/src/main/AndroidManifest.xml

[Please link jira ticket here](https://bugster.forgerock.org/jira/browse/SDKS-2076)
- Update sample App to support broadcast
- Refactor broadcast event to SingleSignOnManager, so whenever revoking the SSO Token, logout event will be broadcast to the SSO Group

SDKS-2076 Changing dynamic configuration in one app does not logout user from other apps in the SSO group

---

forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-auth/src/test/java/org/forgerock/android/auth/SocialLoginTest.java
forgerock-authenticator/build.gradle
forgerock-core/build.gradle
samples/auth/build.gradle
samples/authenticator/build.gradle
samples/authenticator/src/main/java/org/forgerock/authenticator/sample/controller/AuthenticatorModel.java

[SDKS-2097](https://bugster.forgerock.org/jira/browse/SDKS-2097)
Even upgrading to the latest dependency libraries from Google, Google libraries still depend on order version of  'com.google.android.gms:play-services-basement', to resolve the vulnerabilities issue, explicitly include the latest version of  'com.google.android.gms:play-services-basement:18.1.0' is required
The following components have been tested with the upgraded Google Libraries:
- Captcha Node
- Capture Device Location
- Social Login with Google
- Centralize Login

SDKS-2097 Fix Google dependency vulnerabilities in the SDK

---

CHANGELOG.md
README.md
forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-authenticator/build.gradle
forgerock-core/build.gradle
gradle.properties
samples/auth/build.gradle
samples/authenticator/build.gradle
samples/kotlin/build.gradle
samples/quickstart/build.gradle

[SDKS-2103](https://bugster.forgerock.org/jira/browse/SDKS-2103) "ForgeRock Android SDK 3.4.0 Release"
Release preparation for the Android SDK 3.4.0 release.

ForgeRock Android SDK 3.4.0 Release preparation

---

forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/CallbackFragmentFactory.java
forgerock-auth-ui/src/main/java/org/forgerock/android/auth/ui/callback/DeviceSigningVerifierCallbackFragment.java
forgerock-auth-ui/src/main/res/layout/fragment_device_signing_verifier_callback.xml
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticationTests.kt

[Please link jira ticket here](https://bugster.forgerock.org/jira/browse/SDKS-2143)
Add expiration time to JWS for Device Binding and Device Signing Verifier

SDKS-2143 Add expiration time to JWS for Device Binding and Device Signing Verifier

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.kt
samples/auth/src/main/AndroidManifest.xml
samples/authenticator/src/main/res/xml/network_security_config.xml
samples/quickstart/src/main/AndroidManifest.xml

…
[Please link jira ticket here](https://bugster.forgerock.org/jira/browse/SDKS-2132)
SDKS-2132 Attributes under DeviceSigningVerifier and DeviceBinding Callback should be read-only accessible for developer

SDKS-2132 Attributes under DeviceSigningVerifier and DeviceBinding Callback should be read-only accessible for developer

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java

[SDKS-2132](https://bugster.forgerock.org/jira/browse/SDKS-2132)
Some test cases got broken after we merged [PR #203](https://github.com/ForgeRock/forgerock-android-sdk/pull/203)
This PR fixes the test cases.

SDKS-2132 Fix "Device Signing Verifier" e2e tests

---

samples/kotlin/src/main/java/com/forgerock/kotlinapp/MainActivity.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/NodeDialogFragment.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/UserInfoFragment.kt

SDKS-2227 

---

.whitesource

Enable the Mend SCA scan for this Github project and the develop branch
[RELENG-1924](https://bugster.forgerock.org/jira/browse/RELENG-1924)
Enable the Mend SCA scan for this Github project and the develop branch

RELENG-1924 Update .whitesource

---

.whitesource

For the Github projects, no need to specify the projectToken. The projects are automatically created in the Mend "ForgeRock Github" org.
https://bugster.forgerock.org/jira/browse/RELENG-1924
See above.

RELENG-1924 Remove the projectToken

---

forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushNotification.java

…led.
SDKS-2289
Allow fingerprint retry when fingerprint authentication failed

SDKS-2289 Allow fingerprint retry when fingerprint authentication failed

---

build.gradle
config/javadoc.gradle
config/kdoc.gradle
forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-authenticator/build.gradle
forgerock-core/build.gradle

To run the Code use
./gradlew dokkaHtml dokkaHtmlMultiModule
./gradlew dokkaHtml
./gradlew dokkaJavadoc

SDKS 2123 - KDOC

---

forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticator.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticatorTest.kt
forgerock-core/src/main/java/org/forgerock/android/auth/AppPinAuthenticator.kt
forgerock-core/src/main/java/org/forgerock/android/auth/EncryptedFileKeyStore.kt
forgerock-core/src/main/java/org/forgerock/android/auth/KeyStoreRepository.kt
forgerock-core/src/test/java/org/forgerock/android/auth/AppPinAuthenticatorTest.kt

SDKS-2282 - fix to devicebind failure in Android 7 using PKCS12

---

forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
samples/auth/build.gradle
samples/kotlin/build.gradle

https://bugster.forgerock.org/jira/browse/SDKS-2267
SDKS-2267 Update Google Fido version

SDKS-2267 Update Google Fido version

---

forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/WebAuthnFragment.kt

https://bugster.forgerock.org/jira/browse/SDKS-2340
SDKS-2340 Potential fix for fullscreen Biometric Prompt

SDKS-2340 Potential fix for fullscreen Biometric Prompt

---

CHANGELOG.md
gradle.properties

[SDKS-2342](https://bugster.forgerock.org/jira/browse/SDKS-2342) ForgeRock Android SDK 4.0.0-beta3 Release
- Updated CHANGELOG.md and updated version number

ForgeRock Android SDK 4.0.0-beta3 release preparation

---

forgerock-auth/src/main/java/org/forgerock/android/auth/FRUserKeys.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/SharedPreferencesDeviceRepository.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/UserDeviceKeyService.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/UserDeviceKeyServiceTest.kt

[SDKS-2293](https://bugster.forgerock.org/jira/browse/SDKS-2293)
SDKS-2293 Developer interface to unbind device

SDKS-2293 Developer interface to unbind device

---

forgerock-auth/src/main/java/org/forgerock/android/auth/FRUserKeys.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/SharedPreferencesDeviceRepository.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/UserDeviceKeyService.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/UserDeviceKeyServiceTest.kt

https://bugster.forgerock.org/jira/browse/SDKS-2293
Developer interface to unbind device

SDKS-2293-2 Developer interface to unbind device

---

forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/SharedPreferencesDeviceRepositoryTests.kt

SDKS-2293-3 Fix compile failure and refactor test case.

SDKS-2293-3 Fix compile failure and refactor test case.

---

samples/app/build.gradle

The OSS Index scan alert with library vulnerabilities warning
Found vulnerabilities in 1 dependencies
[1/1] - pkg:maven/com.google.android.gms/play-services-basement@18.0.0 - 2 vulnerabilities found!
Upgrade the latest version of play-services-basement

Force update play-services-basement dependency

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingListAndUnbind.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUserKeys.kt
samples/app/src/main/java/com/example/app/callback/binding/CustomAppPinDeviceAuthenticator.kt
samples/app/src/main/java/com/example/app/env/EnvViewModel.kt

[SDKS-2293](https://bugster.forgerock.org/jira/browse/SDKS-2293) "Developer interface to unbind device"
- Added an e2e test case for listing and deleting keys from the device
- Minor enhancements for the Jetpack sample app

e2e test case for list and delete keys from device (SDKS-2293)

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingListAndUnbind.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierApplicationPinCallbackTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticator.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindingStatus.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticatorTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticationTests.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/UserDeviceKeyServiceTest.kt
samples/app/build.gradle
samples/app/src/main/java/com/example/app/MainActivity.kt
samples/app/src/main/java/com/example/app/MainViewModel.kt
samples/app/src/main/java/com/example/app/callback/DeviceSigningVerifierCallback.kt
samples/app/src/main/res/values/splash.xml
samples/app/src/main/res/values/themes.xml

https://bugster.forgerock.org/jira/browse/SDKS-2354
Align device binding error handling with iOS

SDKS-2354 Align device binding error handling with iOS

---

CHANGELOG.md
gradle.properties

[SDKS-2377](https://bugster.forgerock.org/jira/browse/SDKS-2377) ForgeRock Android SDK 4.0.0-beta4 Release

ForgeRock Android SDK 4.0.0-beta4 release preparation

---

CHANGELOG.md
samples/app/build.gradle
samples/app/src/main/java/com/example/app/callback/PollingWaitCallback.kt

Update Change log for removing Native SSO

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.java
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/Attestation.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticator.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/SerializableTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/ApplicationPinDeviceAuthenticatorTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticationTests.kt
forgerock-core/src/main/java/org/forgerock/android/auth/CryptoKey.kt
samples/app/src/main/java/com/example/app/callback/DeviceSigningVerifierCallback.kt
samples/app/src/main/java/com/example/app/env/EnvViewModel.kt
samples/app/src/main/java/com/example/app/journey/Journey.kt
samples/app/src/main/java/com/example/app/userkeys/UserKeysViewModel.kt

[SDKS-2413](https://bugster.forgerock.org/jira/browse/SDKS-2413)
Android Key Attestation Implementation

SDKS-2413 Android Key Attestation Implementation

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
samples/app/src/main/java/com/example/app/userprofile/UserProfile.kt
samples/app/src/main/java/com/example/app/userprofile/UserProfileState.kt
samples/app/src/main/java/com/example/app/userprofile/UserProfileViewModel.kt

[SDKS-2412
](https://bugster.forgerock.org/jira/browse/SDKS-2412)
Set default to Attestation None when server does not provide the attestation attribute.

SDKS-2413 Android Key Attestation Implementation - Set default to Attestation None when server does not provide the attestation attribute.

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/Account.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/AccountTest.java

[SDKS-2446](https://bugster.forgerock.org/jira/browse/SDKS-2446) Error deserializing Account object
The deserialize method on Account object is returning null as String ("null") for some optional attributes.

SDKS-2446 Error deserializing Account object

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/BaseDeviceBindingTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/KeyAttestationTest.java

[SDKS-2437](https://bugster.forgerock.org/jira/browse/SDKS-2437) Device Binding Key Attestation QA
Test cases covering the Application ID and Key Attestation features. 
The key attestation test cases require the following tree present in AM:

SDKS-2437 Device Binding Application Id and Key Attestation e2e Tests

---

CHANGELOG.md
forgerock-auth/src/main/AndroidManifest.xml
forgerock-auth/src/main/java/org/forgerock/android/auth/collector/NetworkCollector.java
samples/quickstart/src/main/AndroidManifest.xml

Updated NetworkCollector to include a more complete network connectivity test
[SDKS-2445](https://bugster.forgerock.org/jira/browse/SDKS-2445)

SDKS-2445_Updates to NetworkCollector 

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushParser.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushParserTest.java

[SDKS-2468](https://bugster.forgerock.org/jira/browse/SDKS-2468) Combined MFA Registration issue with non-default Issuer
[SDKS-2469](https://bugster.forgerock.org/jira/browse/SDKS-2469) Logo image not showing up when registering combined MFA account
Combined MFA Registration parsing issues affecting "issuer" and "image" parameters

SDKS-2468 Combined MFA Registration issue with non-default Issuer

---

.github/pull_request_template.md
.github/workflows/bitbar-results.yaml
.github/workflows/ci.yaml
.github/workflows/publish-snapshot.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
CHANGELOG.md
build.gradle

[SDKS-2369](https://bugster.forgerock.org/jira/browse/SDKS-2369) Publish SNAPSHOT Release

SDKS-2369 Publish SNAPSHOT Release

---

forgerock-core/src/main/java/org/forgerock/android/auth/EncryptedFileKeyStore.kt

[SDKS-2511](https://bugster.forgerock.org/jira/browse/SDKS-2511)
SDKS-2511 Use single master key for Application Pin encryption

SDKS-2511 Use single master key for Application Pin encryption

---

CHANGELOG.md
gradle.properties

[SDKS-2516](https://bugster.forgerock.org/jira/browse/SDKS-2516) ForgeRock Android SDK 4.0.0 Release

ForgeRock Android SDK 4.0.0 release preparation

---

forgerock-authenticator/src/main/java/org/forgerock/android/auth/OathParser.java
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushParser.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/AuthenticatorManagerTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/FRAClientTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/OathFactoryTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/OathParserTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushFactoryTest.java
forgerock-authenticator/src/test/java/org/forgerock/android/auth/PushParserTest.java

[SDKS-2542](https://bugster.forgerock.org/jira/browse/SDKS-2542) Combined MFA Registration not working properly
Issue on parsing Issuer parameter from `mfauth` scheme

SDKS-2542 

---

.github/dependabot.yml

[SDKS-2458](https://bugster.forgerock.org/jira/browse/SDKS-2458) Add Dependabot to the Android CI/CD pipeline
Introducing dependabot

[SDKS-2458] Dependabot condfiguration

---

build.gradle
forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-core/build.gradle
samples/auth/build.gradle
samples/kotlin/build.gradle

Upgrading some dependency libraries to fix security issues in sample apps

---

forgerock-core/src/main/java/org/forgerock/android/auth/EncryptedSharedPreferences.kt
samples/app/build.gradle

(https://bugster.forgerock.org/jira/browse/SDKS-2576)
https://forgerock.zendesk.com/agent/tickets/94902

SDKS 2576 - WebAuthn Lost credentials

---

CHANGELOG.md
gradle.properties

[SDKS-2596](https://bugster.forgerock.org/jira/browse/SDKS-2596) ForgeRock Android SDK 4.1.0 Release

ForgeRock Android SDK 4.1.0 release preparation

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/WebAuthnAuthenticationCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/WebAuthnRegistrationCallback.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/MainActivity.kt

SDKS-2674 bug fix null pointer

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/WebAuthnAuthenticationCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/WebAuthnRegistrationCallback.kt
samples/kotlin/src/main/java/com/forgerock/kotlinapp/MainActivity.kt

test webauthn

---

forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticationTests.kt

[SDKS-2747](https://bugster.forgerock.org/jira/browse/SDKS-2747)
Add iat and nbf claims for Device Binding and Design Signing signed JWT

SDKS-2747 Add iat and nbf claims for Device Binding and Design Signing signed JWT

---

CHANGELOG.md
gradle.properties

[SDKS-2733](https://bugster.forgerock.org/jira/browse/SDKS-2733) ForgeRock Android SDK 4.2.0 Release

ForgeRock Android SDK 4.2.0 release preparation

---

config/kdoc.gradle
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingListAndUnbind.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierApplicationPinCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/KeyAttestationTest.java

[SDKS-2766](https://bugster.forgerock.org/jira/browse/SDKS-2766) Cloud Device Binding Testing 
There were a couple of changes in the Key Attestation feature introduced recently. 
The changes in the PR fix the test cases related to that.

SDKS-2766 Fixed key attestation test cases

---

forgerock-auth/build.gradle
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/ReCaptchaCallback.java
forgerock-auth/src/main/java/org/forgerock/android/auth/idp/AppleSignInHandler.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/ReCaptchaCallbackTest.kt
forgerock-core/build.gradle
gradle.properties
samples/app/build.gradle
samples/app/src/main/java/com/example/app/callback/ReCaptchaCallback.kt
samples/app/src/main/java/com/example/app/journey/Journey.kt
samples/auth/build.gradle

SDKS-2701 - remove jetifier

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceBindingCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallback.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/BiometricAndDeviceCredential.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/BiometricAuthenticator.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/BiometricBindingHandler.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/BiometricOnly.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticators.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/DeviceBindingStatus.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/None.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/RSASASignatureSigner.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/BiometricBindingHandlerTests.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/DeviceBindAuthenticationTests.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/devicebind/RSASASignatureSignerTests.kt
forgerock-authenticator/src/main/java/org/forgerock/android/auth/PushNotification.java
forgerock-core/src/main/java/org/forgerock/android/auth/CryptoKey.kt
forgerock-core/src/main/java/org/forgerock/android/auth/biometric/BiometricAuth.kt
samples/app/build.gradle

[SDKS-2797](https://bugster.forgerock.org/jira/browse/SDKS-2797)
Switch to use auth-per-use Key for Device Binding

SDKS-2797 Switch to use auth-per-use Key for Device Binding

---

build.gradle
forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle
forgerock-authenticator/build.gradle
forgerock-core/build.gradle
samples/app/build.gradle
samples/auth/build.gradle
samples/kotlin/build.gradle

SDKS-2751 WoodStox + security vulnerability improvements

---

forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceBindingCallbackTest.java
forgerock-auth/src/androidTest/java/org/forgerock/android/auth/callback/DeviceSigningVerifierCallbackTest.java

[SDKS-2787](https://bugster.forgerock.org/jira/browse/SDKS-2787)  Add custom claims to device signing JWT
- Added test coverage for custom claims 
- Added test coverage for `DeviceBinding.DEVICE` and `DeviceSigningVerifierNode.JWT` variables in AM

SDKS-2787 Test coverage for custom claims

---

CHANGELOG.md
gradle.properties

[SDKS-2854](https://bugster.forgerock.org/jira/browse/SDKS-2854) ForgeRock Android SDK 4.3.0 Release
- Updated `CHANGELOG.md`
- Update version number in `gradle.properties` file

ForgeRock Android SDK 4.3.0 Release Preparation

---

forgerock-auth/src/main/java/org/forgerock/android/auth/callback/AppIntegrityCallback.kt

Update doc for AppIntegrityCallback class.

Update doc for AppIntegrityCallback

---

forgerock-auth/src/test/java/org/forgerock/android/auth/BrowserLoginTest.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java

[SDKS-3015 ](https://bugster.forgerock.org/jira/browse/SDKS-3015) SDK 4.4.0 Release Testing
- Fixed certificate pinning unit tests

SDKS-3015 SDK 4.4.0 Release Testing

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/AppAuthConfigurer.java
forgerock-auth/src/main/java/org/forgerock/android/auth/AppAuthFragment.java
forgerock-auth/src/main/java/org/forgerock/android/auth/AppAuthFragment2.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/AuthorizeContract.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/FRUser.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.java
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/BrowserLauncher.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/Launcher.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/BrowserLoginTest.kt
samples/app/src/main/java/com/example/app/MainActivity.kt
samples/app/src/main/java/com/example/app/centralize/CentralizeLoginViewModel.kt
samples/auth/src/main/java/org/forgerock/auth/MainActivity.java

[SDKS-3079](https://bugster.forgerock.org/jira/browse/SDKS-3079)
Replace deprecated onActivityResult with ActivityResultContract

SDKS-3079 Replace deprecated onActivityResult with ActivityResultContract

---

samples/app/src/main/java/com/example/app/setting/SettingRoute.kt
samples/app/src/main/java/com/example/app/setting/SettingViewModel.kt

[SDKS-3199](https://bugster.forgerock.org/jira/browse/SDKS-3199)
Synchronize the encryption and decryption block to avoid keystore crash.

SDKS-3199 Synchronize the encryption and decryption block to avoid keystore crash.

---

forgerock-auth/src/main/java/org/forgerock/android/auth/DefaultTokenManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/OAuth2Client.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/SessionManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/TokenManager.java
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/AppAuthFragment2.kt
samples/app/src/main/java/com/example/app/env/EnvViewModel.kt
samples/app/src/main/java/com/example/app/token/Token.kt
samples/app/src/main/java/com/example/app/token/TokenViewModel.kt

[SDKS-3282](https://bugster.forgerock.org/jira/browse/SDKS-3282)
- FRUser.revokeAccessToken() should NOT end user's session
- Browser logout should not invoke endSession endpoint directly

SDKS-3282 FRUser.revokeAccessToken() should NOT end user's session

---

forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/DefaultStorageClientStressTest.java

[SDKS-3229](https://bugster.forgerock.org/jira/browse/SDKS-3229) Functional Testing of Authenticator module using SecureSharedPreferences Changes
We need to ensure that the changes performed in [SDKS-3199](https://bugster.forgerock.org/jira/browse/SDKS-3199), have no impact on the Authenticator module of the SDK.

SDKS-3229 DefaultStorageClient Stress Test

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/AuthorizeContract.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/centralize/EndSessionContract.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
samples/app/src/main/java/com/example/app/env/EnvViewModel.kt

https://bugster.forgerock.org/jira/browse/SDKS-3346
Resolve potential CustomTabManager ServiceConnection leak.

SDKS-3346 Potential CustomTabManager ServiceConnection leak.

---

CHANGELOG.md
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/AndroidBuildGradlePlugin.kt
forgerock-auth-ui/build.gradle
forgerock-auth/build.gradle.kts
forgerock-auth/src/main/java/org/forgerock/android/auth/webauthn/WebAuthnRegistration.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/ServerConfigTest.java
forgerock-auth/src/test/java/org/forgerock/android/auth/callback/AppIntegrityCallbackTest.kt
forgerock-core/build.gradle.kts
forgerock-integration-tests/build.gradle.kts
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
ping-protect/build.gradle.kts
samples/app/build.gradle.kts
samples/app/proguard-rules.pro
samples/app/src/main/java/com/example/app/callback/DeviceSigningVerifierCallback.kt
samples/auth/build.gradle
samples/authenticator/build.gradle
samples/kotlin/build.gradle
samples/quickstart/build.gradle
samples/quickstart/src/main/AndroidManifest.xml

[SDKS-3098](https://bugster.forgerock.org/jira/browse/SDKS-3098)
- Update CompileSDK to API 35
- Upgrade all libraries to the latest version (except firebase-messaging)
- Test and resolve compile issue after upgrade

SDKS-3098 Support Android 15

---

samples/app/src/main/java/com/example/app/env/EnvViewModel.kt

[SDKS-3420](https://bugster.forgerock.org/jira/browse/SDKS-3420)
SDKS-3420 Use sample environment for Sample App.

SDKS-3420 Use sample environment for Sample App.

---

samples/app/build.gradle.kts

[SDKS-3435](https://bugster.forgerock.org/jira/browse/SDKS-3435)
Use JVM Tool Chain to specify the language version.

SDKS-3435 Use JVM Tool Chain to specify the language version.

---

samples/app/src/main/java/com/example/app/AppDrawer.kt
samples/app/src/main/java/com/example/app/AppNavHost.kt
samples/app/src/main/java/com/example/app/Destinations.kt
samples/app/src/main/java/com/example/app/callback/AttributeInput.kt
samples/app/src/main/java/com/example/app/callback/BooleanAttributeInputCallback.kt
samples/app/src/main/java/com/example/app/callback/KbaCreateCallback.kt
samples/app/src/main/java/com/example/app/callback/NumberAttributeInputCallback.kt
samples/app/src/main/java/com/example/app/callback/StringAttributeInputCallback.kt
samples/app/src/main/java/com/example/app/callback/TermsAndConditionsCallback.kt
samples/app/src/main/java/com/example/app/env/EnvViewModel.kt
samples/app/src/main/java/com/example/app/journey/Journey.kt

Enhance Sample App to support IDM related Callbacks.

Enhance Sample App to support IDM related Callbacks.

---

samples/app/src/main/java/com/example/app/callback/ReCaptchaEnterpriseCallback.kt
samples/app/src/main/java/com/example/app/journey/Journey.kt

Fix for Captcha Enterprise with supporting pagenode

---

CHANGELOG.md
forgerock-auth/src/main/java/org/forgerock/android/auth/Config.java
forgerock-auth/src/main/java/org/forgerock/android/auth/ServerConfig.java
forgerock-auth/src/main/java/org/forgerock/android/auth/selfservice/Session.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/selfservice/UserRepository.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/selfservice/UserRepositoryMockTest.kt
forgerock-auth/src/test/resources/selfservice/accessDenied.json
forgerock-auth/src/test/resources/selfservice/forbidden.json
forgerock-auth/src/test/resources/selfservice/sessionInfo.json
forgerock-auth/src/test/resources/selfservice/successDeviceBinding.json
forgerock-auth/src/test/resources/selfservice/successDeviceProfile.json
forgerock-auth/src/test/resources/selfservice/successOath.json
forgerock-auth/src/test/resources/selfservice/successPush.json
forgerock-auth/src/test/resources/selfservice/successUpdateDeviceBinding.json
forgerock-auth/src/test/resources/selfservice/successUpdateDeviceProfile.json
forgerock-auth/src/test/resources/selfservice/successUpdateWebAuthn.json
forgerock-auth/src/test/resources/selfservice/successWebAuthn.json
gradle/libs.versions.toml
samples/app/build.gradle.kts
samples/app/src/main/AndroidManifest.xml
samples/app/src/main/java/com/example/app/Alert.kt
samples/app/src/main/java/com/example/app/AppDrawer.kt
samples/app/src/main/java/com/example/app/AppNavHost.kt
samples/app/src/main/java/com/example/app/Destinations.kt
samples/app/src/main/java/com/example/app/selfservice/SelfServiceRoute.kt
samples/app/src/main/java/com/example/app/selfservice/SelfServiceState.kt
samples/app/src/main/java/com/example/app/selfservice/SelfServiceViewModel.kt

[SDKS-3408](https://pingidentity.atlassian.net/browse/SDKS-3408)
Self Device Management Service
```kotlin
val oathDevices: List<OathDevice> = userRepository.oathDevice()
val pushDevices: List<PushDevice> = userRepository.pushDevice()
val webAuthnDevices: List<WebAuthnDevice> = userRepository.webAuthnDevice()
val bindingDevice: List<BindingDevice> = userRepository.bindingDevice()
val profileDevice: List<ProfileDevice> = userRepository.profileDevice()
//Update Device Name
webAuthnDevices[0].deviceName = "New Device Name"
userRepository.update(webAuthnDevices[0])
//Delete Device
userRepository.delete(webAuthnDevices[0])
```
Sample App Update:

SDKS-3408 Self device management implementation

---

forgerock-auth/src/main/java/org/forgerock/android/auth/selfservice/DeviceClient.kt
forgerock-auth/src/test/java/org/forgerock/android/auth/selfservice/DeviceClientMockTest.kt
samples/app/src/main/java/com/example/app/selfservice/SelfServiceViewModel.kt

[SDKS-3541](https://pingidentity.atlassian.net/browse/SDKS-3541)
Align Device Self service naming with iOS SDK

SDKS-3541 Align Device Self service naming with iOS SDK

---

.github/pull_request_template.md
CONTRIBUTION.md
README.md

[SDKS-3641](https://pingidentity.atlassian.net/browse/SDKS-3641) Clearly define external guidelines for PRs against SDKs
We need to make the guidelines and standards for external contributions more clear.

SDKS-3641 Clearly define external guidelines for PRs against SDKs

---

forgerock-auth/src/main/java/org/forgerock/android/auth/CookieMarshaller.java
forgerock-auth/src/main/java/org/forgerock/android/auth/FRAuth.java
forgerock-auth/src/main/java/org/forgerock/android/auth/devicebind/BiometricOnly.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/storage/CookiesStorage.kt
forgerock-auth/src/main/java/org/forgerock/android/auth/storage/SSOTokenStorage.kt
forgerock-core/src/main/java/org/forgerock/android/auth/SecuredSharedPreferences.java
forgerock-core/src/main/java/org/forgerock/android/auth/encrypt/SecretKeyEncryptor.kt

[SDKS-3990](https://pingidentity.atlassian.net/browse/SDKS-3990)
SDKS-3990 Address missing error and warning exception logging. This change ensures these critical events are properly recorded.

SDKS-3990 Address missing error and warning exception logging. This change ensures these critical events are properly recorded.

---

.github/workflows/mend-cli-scan.yaml

[SDKS-3975](https://pingidentity.atlassian.net/browse/SDKS-3975) Release activities for ForgeRock SDK 4.8.0 
- Temporary disable the Mend SAST report generation

Disable Mend reports temporary

---

.github/workflows/bitbar-prepare-artifacts.yaml
.github/workflows/ci.yaml
forgerock-integration-tests/build.gradle.kts
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/AndroidBaseTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/TestConfig.kt
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/AppIntegrityCallbackTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/BaseDeviceBindingTest.java
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/BasePingOneProtectTest.kt
forgerock-integration-tests/src/androidTest/java/org/forgerock/android/auth/callback/ReCaptchaEnterpriseCallbackBaseTest.kt
forgerock-integration-tests/src/main/assets/test_config.properties

[SDKS-3974](https://pingidentity.atlassian.net/browse/SDKS-3974)
SDKS-3974 Introduce a dedicated test configuration file to better manage environment-specific settings. This allows for easier switching between different test environments without modifying core test files.

SDKS-3974 Introduce a dedicated test configuration file to better manage environment-specific settings.
